### ISSUE TITLE
Licence: Vanilla.bash under GPL?

### ISSUE THREAD

**Issue by Explorer09** [Lin-Buo-Ren/GNU-Bash-Shell-Script-Template#15]
The Vanilla.bash template (including [this](https://github.com/Lin-Buo-Ren/Vanilla.bash), not including the documentation) should be ineligible for copyright and be in public domain.
I am not a lawyer, but I guess such a bad licensing can indicate you are not serious enough for the project.

**Comment by Lin-Buo-Ren** [comment]
This is the licensing terms of GBSST: 

```
GNU General Public License v3+ with an exception of only using this software as a template of a shell script(which you can use any license you prefer, attribution appreciated)

This means that GPL is enforced only when you're making another "shell script template" using this software, which you're demanded to also using GPL for your work
```

The GPL license isn't enforced at all if you use the template as a template, which of course includes the Vanilla.bash script.

For [Lin-Buo-Ren/Vanilla.bash](https://github.com/Lin-Buo-Ren/Vanilla.bash) the only reason that the GPL is used is to hide the remarks by the entensive length license text.

**Comment by Explorer09** [comment]
So the license ambiguity was intentional, huh?
Dammit. If you wanted to conceal some footnotes, then [CC0](https://creativecommons.org/publicdomain/zero/1.0/legalcode) can be long and boring enough. Otherwise, I'll expect something meaningful be written, such as an FAQ, especially about why the template was nothing but a shebang line and some dummy comments.
